### PR TITLE
Prepared build scripts for Node 10 migration

### PR DESCRIPTION
**Pull request by egor-bryzgalov**
**Task name**: none

**Description**: 

- Changed build scripts to allow typescript version overriding and installing specified node version to run task tests;
- Renamed tasks' folders;
- Updated `make-options.json`;

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** [#677](https://github.com/microsoft/build-task-team/issues/677)

**Checklist**:
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by egor-bryzgalov** [comment]
Tested gulp build and gulp test commands. Checked tsc version is overridden correctly while building. Checked that node version is installed automatically. All unit tests passed. Unit tests have also be checked for different Node execution handler.

**Review by DaniilShmelev — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
Let's test this agains on prem also.

**Comment by egor-bryzgalov** [comment]
Tested:
✔️ gulp build
✔️ gulp test
✔️ gulp create
✔️ Installing to the latest on-premise AzDO server as an update to pre-installed extension from the marketplace.
             ✔️ Checked that tasks are replaced after update

**Comment by alexander-smolyakov** [comment]
**Tested**: 
- All gulp commands tested  by simple Powershell script 
- Successfully uploaded `Google Play - Release` task to DevOrg via tfx-cli.  
- Test pipeline successfully passed: https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2426&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ec573ef3-cde4-5c11-ae6d-241f58863357

**Script for testing**:
```PowerShell
$(
    Write-Host "#############################################################################"
    $command = 'gulp build'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp test'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp build --task GooglePlayPromote'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp test --task GooglePlayPromote'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp build --task GooglePlayRelease'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp test --task GooglePlayRelease'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp build --task GooglePlayReleaseBundle'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp test --task GooglePlayReleaseBundle'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp build --task GooglePlayRolloutUpdate'
    Invoke-Expression $command
    Write-Host "#############################################################################"

    Write-Host "#############################################################################"
    $command = 'gulp test --task GooglePlayRolloutUpdate'
    Invoke-Expression $command
    Write-Host "#############################################################################"
) *>&1 > test_gulp.log
``` 
**Script logs**:
[test_gulp.log](https://github.com/microsoft/google-play-vsts-extension/files/5893285/test_gulp.log)

**Review by alexander-smolyakov — APPROVED** [review]

**Pull request merged**
