### PR TITLE
Feature: release bundle

### LINKED ISSUE #100: [Feature Request] Upload Android App Bundle, .aab files
There are now API's available for uploading the new Android App Bundle format:
https://developers.google.com/android-publisher/api-ref/edits/bundles/upload

It would be great to have this ability in our CI environment.

### PR DESCRIPTION
**Pull request by ddfreiling**
This adds a separate task for releasing an Android Bundle (.aab) file. I just took the old release task, stripped it to its essentials and removed the APK-related parameters.

I had to add the `packageName` input, since the APK inspector tool could no longer give us the application identifier from the bundle.

I haven't worked on VSTS tasks before, so I'm not sure what UUID to give the task and why all the `googleapis` types were unnecessarily repeated in `googleutils.ts`. I just imported the types distributed with the `googleapis` package under the `androidpublisher_v3` namespace instead. 

Please review thoroughly and do not hesitate to request changes.

I fixed up the tests and tested it manually with a new version of an app of mine.

Fixes #100

### CODE REVIEW

**Comment by ddfreiling** [comment]
@AlexRukhlin @lkillgore Any of you guys know who is maintaining this repo now?

**Comment by leantk** [comment]
@ddfreiling sorry we've had a team switch so we are ramping up on this. Please give us a few days and I will get a review to you. Just want to be sure we have the proper people looking at it. Thanks!

**Comment by sfratini** [comment]
@ddfreiling This is very interesting! I gave up on my code because like you said the problem was getting the package name but I never thought about adding it as an input. Nice work. In the meantime I am using fastlane to upload AAB.

**Comment by leantk** [comment]
@ddfreiling I have somebody working on testing out the changes now on our end but it will take some setup. Like I said it is a new area for people so I apologize for the delay but we haven't forgot about this. The timing was just bad in this case :-(

**Comment by ddfreiling** [comment]
@erjohnms I've now done so. Should the major version on the release-bundle task be 1, since it's a new task?

**Comment by erjohnms** [comment]
@ddfreiling I think its fine to leave it as is

**Comment by slang25** [comment]
This looks great. I've just tried it for the first time, copying the previous APK release task, and adding in and tweaking the values as required and am getting this:
image

Any ideas? Happy to open a separate issue.

**Comment by ValueRRE** [comment]
Same thing happens to me and until now i don't have a clou how to get around it. Any ideas how to get it to work?

**Comment by slang25** [comment]
Are you able to run it again with the system.debug variable set to true? It will likely contain some more useful output. I won't be able to until next week unfortunately.

**Comment by ValueRRE** [comment]
I already did that, for me it looks like the following:
grafik

Unfortunatelly, this output was not helpful for me :(

**Comment by slang25** [comment]
Yeah, hard to infer much from that. Thanks anyway! @ddfreiling any suggestions here? I'll do a little investigating, but I'm a little out of my comfort zone here.

**Comment by ddfreiling** [comment]
I will look into this when possible. I'm unsure if the corrections from #140, which fixed the broken task json has actually landed on the agents. Do you know?

**Comment by slang25** [comment]
I can confirm that #140 made it in, as a the following change bumped the version number (#141) and this is the version that is live.

**Comment by slang25** [comment]
Linking to issue #142

**Pull request merged**
