### PR TITLE
[GooglePlayRelease] Update dependencies

### PR DESCRIPTION
**Pull request by EzzhevNikita**
**Task name**: GooglePlayRelease

**Description**: 
* Updated _googleapis_ to 67.1.0 to resolve vulnerabilities in depended packages.
* Updated _google-auth-library_ to 7.0.2 to resolve vulnerabilities in depended packages.
* Updated _azure-pipelines-task-lib_ to 3.1.0 to use not preview version

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/google-play-vsts-extension/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

[Reference ](https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2966&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9) to test pipeline

### CODE REVIEW

**Comment by DaniilShmelev** [comment]
Could there be any regressions associated with updating googleapis and google-auth-library?

**Review by anatolybolshakov — APPROVED** [review]
LGTM, but let's test this accurately since there are risky dependency updates.

**Comment by EzzhevNikita** [comment]
> Could there be any regressions associated with updating googleapis and google-auth-library?

I think there no changes that affecting our tasks behavior, from googleapis lib our tasks are using only [@googleapis/androidpublisher ](https://github.com/googleapis/google-api-nodejs-client/releases/tag/androidpublisher-v0.2.0) package, the previous version of googleapis lib has androidpublisher v0.1.0. Based on the release notes there no breaking changes in the new version of this package.

Regarding the google-auth-library, based on the [release notes](https://github.com/googleapis/google-auth-library-nodejs/tags) in their repo there some breaking changes in this lib between v2 and v7, but looking at the way we are using google-auth-library, these changes shouldn't affect our tasks.

**Review by matskan — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
Tested changes also, LGTM!

**Pull request merged**
