### PR TITLE
Add deobfuscation file upload support

### PR DESCRIPTION
**Pull request by NxSoftware**
## Description

* Updates the [`google-api-nodejs-client`](https://github.com/googleapis/google-api-nodejs-client) dependency in order to get client library support for uploading deobfuscation files.
* Add support for uploading a deobfuscation (mapping.txt) file. Only 1 file is supported at this time and it is associated with the main APK file.
* Removed interfaces defined in the Release task in favour of using those in `google-api-nodejs-client`.
* Removed deprecated [`typings`](https://github.com/typings/typings) library.

Tested as working, uploads an APK and the specified mapping.txt file for the main APK file.

## Risks

* Had to remove setting the `uploadType` to `media` in the `uploadImage` function due to it not being present in the latest `google-api-nodejs-client`. Nowhere in the client docs does it appear to be support, however the [Google Play Developer API](https://developers.google.com/android-publisher/api-ref/edits/images/upload#parameters) docs state it as a required query parameter. Unsure if it is necessary to manually add this to the URL, e.g. `?uploadType=media`. Seems like a poor design decision in the `google-api-nodejs-client` if it is.

## Associated Issues

* #14

### CODE REVIEW

**Comment by NxSoftware** [comment]
Can't access the details of that failing build but I tested this manually and it failed:

```

**Comment by jgavazzisp** [comment]
Hi there, could you get any update on this, please?

Thanks

**Comment by NxSoftware** [comment]
@jgavazzisp the changes since my last comment have resolved the issues and the release task has been successfully uploading the deobfuscation file to Google Play.

**Comment by lkillgore** [comment]
Hi @NxSoftware, I apologize for not responding earlier, but I didn't see this until I posted my own changes for review.  This is nice work!  I've made another PR (#134), which includes some of the changes you've made here, but not the obfuscation change.  I can copy the change over in a new PR after I finish my PR and can tag you into the review.  How does that sound?

**Comment by NxSoftware** [comment]
Hi @lkillgore, not to worry. Sounds good to me, hopefully it'll transfer over easy enough :)

**Comment by lkillgore** [comment]
Closing as this is now covered in: #136.

**Pull request closed without merging**
