### PR TITLE
Added missing comma to ps script

### LINKED ISSUE #142: Can't use release aab with yaml
```

##[debug]loading INPUT_METADATAROOTPATH
##[debug]loading INPUT_SHOULDUPLOADMAPPINGFILE
##[debug]loading INPUT_MAPPINGFILEPATH
##[debug]loading INPUT_VERSIONCODEFILTERTYPE
##[debug]loading ENDPOINT_AUTH_7a37d71f-d930-44fb-afea-5ca9e3f7bc82
##[debug]loading ENDPOINT_AUTH_SCHEME_7a37d71f-d930-44fb-afea-5ca9e3f7bc82
##[debug]loading ENDPOINT_AUTH_PARAMETER_7a37d71f-d930-44fb-afea-5ca9e3f7bc82_USERNAME
##[debug]loading ENDPOINT_AUTH_PARAMETER_7a37d71f-d930-44fb-afea-5ca9e3f7bc82_PASSWORD
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 23
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]task result: Failed
##[error]Unhandled: Unexpected identifier
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected identifier
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected identifier
Finishing: Publish to production on Play Store

```

### PR DESCRIPTION
**Pull request by aweFalafelApps**
Any chance this simple correction could fix #142? I'm not super familiar with ADO tasks, but as far as I could tell the ts script worked in my testing.

### CODE REVIEW

**Comment by arctouch-carlosottoboni** [comment]
@erjohnms @ddfreiling

**Comment by ddfreiling** [comment]
Looks good to me, although I have no rights to approve.
Very sorry I didn't catch this error myself in the original implementation, but thanks for fixing it!

**Comment by blundell** [comment]
What's the turnaround/process once this gets merged to it being available through the plugins market?

**Comment by arctouch-carlosottoboni** [comment]
@erjohnms Could you please give some attention to this PR? It's a major issue with a simple fix.

**Comment by woutervs** [comment]
@leantk I saw you have approving power on some previous PR's Maybe you can escalate this?

Sorry if you're not the right person :)

**Comment by michelebonomelli** [comment]
@leantk 

Sorry, but I'm not the right person.
I'm waiting for merge approving, too.

**Comment by woutervs** [comment]
Any Idea when the extension will be updated on the marketplace?
@leantk

**Comment by ddfreiling** [comment]
@leantk 10 days to add a comma... can this be merged and built soon? 😕

**Comment by leantk** [comment]
I'll work on getting this released at the beginning of week. Sorry for the delay :-/

**Comment by slang25** [comment]
Thanks @leantk  😁

**Comment by daniels7** [comment]
@leantk Are there any news on this yet? The release bundle task is still not working sadly

**Comment by slang25** [comment]
It's being worked on, see here: https://github.com/microsoft/google-play-vsts-extension/pull/146#issuecomment-564070885

And the recent subsequent commits

**Comment by daniels7** [comment]
Thank you very much for the Info :)

**Comment by leantk** [comment]
Yes the update to Node and Gulp caused some issues with releasing but I'm rerunning tests and should have it out today. I'm sorry for the delay. The jump from Gulp v3 to Gulp v4 changed forced up to change some things in our Gulpfile to make it work

**Comment by leantk** [comment]
Ok the release is out and again I apologize for the delay. Please let me know if how everything looks from your end

**Comment by michelebonomelli** [comment]
Extension updated to version 3.160.2, but deployment still doesn't work, with the same error: "##[error]Unhandled: Unexpected identifier"

**Comment by aweFalafelApps** [comment]
): that's a bummer! @leantk is there a way to actually test this task locally exactly as it is run in ADO?

**Comment by zimo85** [comment]
I can confirm that version 3.160.2 still does not work on Azure DevOps Server 2019.1.1, as said by @michelebonomelli 
@leantk can you give us a feedback, please?

**Comment by leantk** [comment]
I'm going to have to take a look at it but most likely not today. Could somebody post the entire log for the step so I can see it in it's entirety please?

**Comment by zimo85** [comment]
> I'm going to have to take a look at it but most likely not today. Could somebody post the entire log for the step so I can see it in it's entirety please?

`2019-12-12T13:58:42.1122179Z ##[debug]Evaluating condition for step: 'Release $(System.DefaultWorkingDirectory)/_playLND-aab/drop/app.aab to internal'
2019-12-12T13:58:42.1123572Z ##[debug]Evaluating: succeeded()
2019-12-12T13:58:42.1123742Z ##[debug]Evaluating succeeded:
2019-12-12T13:58:42.1124118Z ##[debug]=> True
2019-12-12T13:58:42.1124528Z ##[debug]Result: True
2019-12-12T13:58:42.1124930Z ##[section]Starting: Release $(System.DefaultWorkingDirectory)/_playLND-aab/drop/app.aab to internal
2019-12-12T13:58:42.1520053Z ==============================================================================
2019-12-12T13:58:42.1520335Z Task         : Google Play - Release Bundle
2019-12-12T13:58:42.1520489Z Description  : Release an app bundle to the Google Play Store
2019-12-12T13:58:42.1520612Z Version      : 3.160.0
2019-12-12T13:58:42.1520728Z Author       : Microsoft Corporation
2019-12-12T13:58:42.1520852Z Help         : ms-resource:loc.helpMarkDown
2019-12-12T13:58:42.1521001Z ==============================================================================
2019-12-12T13:58:42.5428090Z ##[debug]agent.TempDirectory=C:\agent\_work\_temp
2019-12-12T13:58:42.5432567Z ##[debug]loading inputs and endpoints
2019-12-12T13:58:42.5443537Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-12-12T13:58:42.5443857Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-12-12T13:58:42.5444067Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-12-12T13:58:42.5444233Z ##[debug]loading INPUT_APPLICATIONID
2019-12-12T13:58:42.5444395Z ##[debug]loading INPUT_AUTHTYPE
2019-12-12T13:58:42.5444613Z ##[debug]loading INPUT_BUNDLEFILE
2019-12-12T13:58:42.5444771Z ##[debug]loading INPUT_CHANGELOGFILE
2019-12-12T13:58:42.5444951Z ##[debug]loading INPUT_LANGUAGECODE
2019-12-12T13:58:42.5445143Z ##[debug]loading INPUT_MAPPINGFILEPATH
2019-12-12T13:58:42.5445327Z ##[debug]loading INPUT_METADATAROOTPATH
2019-12-12T13:58:42.5445506Z ##[debug]loading INPUT_ROLLOUTTOUSERFRACTION
2019-12-12T13:58:42.5445698Z ##[debug]loading INPUT_SERVICEACCOUNTKEY
2019-12-12T13:58:42.5445873Z ##[debug]loading INPUT_SHOULDATTACHMETADATA
2019-12-12T13:58:42.5446053Z ##[debug]loading INPUT_SHOULDUPLOADMAPPINGFILE
2019-12-12T13:58:42.5446215Z ##[debug]loading INPUT_TRACK
2019-12-12T13:58:42.5446399Z ##[debug]loading INPUT_USERFRACTION
2019-12-12T13:58:42.5446557Z ##[debug]loading INPUT_VERSIONCODEFILTERTYPE
2019-12-12T13:58:42.5446732Z ##[debug]loaded 17
2019-12-12T13:58:42.5446890Z ##[debug]Agent.ProxyUrl=undefined
2019-12-12T13:58:42.5447095Z ##[debug]Agent.CAInfo=undefined
2019-12-12T13:58:42.5447266Z ##[debug]Agent.ClientCert=undefined
2019-12-12T13:58:42.5447441Z ##[debug]Agent.SkipCertValidation=undefined
2019-12-12T13:58:42.5447599Z ##[debug]task result: Failed
2019-12-12T13:58:42.5546613Z ##[error]Unhandled: Unexpected identifier
2019-12-12T13:58:42.5564618Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected identifier
2019-12-12T13:58:42.5604832Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected identifier
2019-12-12T13:58:42.5607057Z ##[section]Finishing: Release $(System.DefaultWorkingDirectory)/_playLND-aab/drop/app.aab to internal
`
[4_Release $(System.DefaultWorkingDirectory)_playLND-aabdropapp.aab to internal.log](https://github.com/microsoft/google-play-vsts-extension/files/3956043/4_Release.System.DefaultWorkingDirectory._playLND-aabdropapp.aab.to.internal.log)

**Comment by michelebonomelli** [comment]
Here the entire log for the step.
I noticed now that version reported in log is 3.160.0, not the same as the extension reported version (3.160.2).

[tasklog_7.log](https://github.com/microsoft/google-play-vsts-extension/files/3956049/tasklog_7.log)

**Comment by anne-k** [comment]
Could it be this?
https://stackoverflow.com/a/58788556/9434434

> In my case, the problem was not updating the task version in task.json file. Updating the extension's version (in the manifest file) is not enough. If the task version does not change, Azure DevOps will not update the task itself (despite correctly updating the extension in the "Extensions" page).

I see none of the task.json files were updated. So if this comment is correct, then the extension itself reports a version update but all the tasks it contains are actually still on the old version.

**Comment by NPadrutt** [comment]
@leantk any chance you could release an updated version of the extension with the task.json adjusted as @anne-k suggested?

**Comment by mortenolsson** [comment]
We would love to have this fix made available as well.

**Comment by leantk** [comment]
Ok I will get on this today. Thanks for the sugestion @anne-k!

**Comment by leantk** [comment]
Ok the update has been made and released. Can somebody please confirm if they see the latest version task used (i.e. 3.163.0) and if that corrects the issue?

**Comment by michelebonomelli** [comment]
Version is updated (3.163.0) in the extensions and in the log, too.
But the problem still remains: "##[error]Unhandled: Unexpected identifier".

**Comment by mayeager22** [comment]
I am using this task for the first time and getting "##[error]Unhandled: Unexpected identifier" issue.

Confirmed version 3.163.0 as well.

**Comment by mortenolsson** [comment]
works for me now - awesome ! :-)

**Comment by daniels7** [comment]
did you change anything else @mortenolsson ? I still get the error

**Comment by mortenolsson** [comment]
nope - but looking at the log I did notice that the version of the task actually running seems to be newer:

2019-12-19T21:49:36.3365790Z Task         : Google Play - Release Bundle
2019-12-19T21:49:36.3366180Z Description  : Release an app bundle to the Google Play Store
2019-12-19T21:49:36.3366520Z Version      : 3.164.0
2019-12-19T21:49:36.3366840Z Author       : Microsoft Corporation

**Comment by daniels7** [comment]
Oh, cool. Sadly in Germany the releases seem to take at least 24 hours longer. I hope tomorrow I'll get 3.164.0 as well

**Comment by mortenolsson** [comment]
I'm in Denmark so it must be close :-)
Best of luck.

**Comment by daniels7** [comment]
Thank you :)

**Comment by mayeager22** [comment]
I can confirm that it is now working in version 3.164.0.

**Comment by woutervs** [comment]
Can also confirm as of 3.164.0 pushing aab's to the playstore works! Tyvm everyone involved.

**Comment by NPadrutt** [comment]
Same here. Thanks everyone! :)

**Comment by teamtam** [comment]
I am on 3.164.0 but I get this error:
`2019-12-21T13:37:48.0353488Z ##[error]Error: error:0906D06C:PEM routines:PEM_read_bio:no start line`

**Pull request merged**
